### PR TITLE
add bind_ip to better listen IP control

### PR DESCRIPTION
**Pull request by mohsenmottaghi**
In my opinion, this small change will help Pro users gain more control over server ports, and users who like to restrict the application via IPTABLES or firewall or make the Reverse Proxy for this application have  more options and are easier to reassure.

### CODE REVIEW

**Comment by erdii** [comment]
We already enable the firewall "UFW" and deny access to wg-dashboard via other interfaces than 127.0.0.1 so this should already be given, right?

**Comment by mohsenmottaghi** [comment]
yes, but many users disable UFW and use iptables

**Comment by erdii** [comment]
UFW uses iptables under the hood, I see no reason why you should not be able to block a port via iptables.

I understand your concern, how would you design usability and reachability of wg-dashboard?
I'd like to listen on 127.0.0.1 and wg0 ip so the dashboard can be reached over vpn without having to configure ssh.

**Comment by mohsenmottaghi** [comment]
I use reverse proxy with IP white-list and Iptables in production environment and to use wg-dashboard in our design so I had to make some changes to it to make it compatible with our production environment. So I thought maybe someone else would have an environment like us, and so I requested this change. But this is a friendly suggestion you can ignore it or poll it from others 

Be happy and OpenSource :)

**Comment by erdii** [comment]
Okay...

Would you mind elaborating how your iptables setup works? Do you listen on localhost and forward trafic from selected ips to localhost:port via iptables?
If so, maybe we could listen on 127.0.0.1 and forward traffic from wg0.

This way we both get what we (and hopefully the other wg-dashboard users) want :)

**Pull request closed without merging**
